/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View2;

/**
 *
 * @author Harude
 */
public class Profile extends javax.swing.JPanel {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taProfile = new javax.swing.JTextArea();
        jProfilePics = new javax.swing.JPanel();
        jTabMedia = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        PhotoList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        VideoList = new javax.swing.JList<>();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(778, 547));

        jScrollPane1.setBorder(null);

        taProfile.setEditable(false);
        taProfile.setBackground(new java.awt.Color(240, 240, 240));
        taProfile.setColumns(20);
        taProfile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        taProfile.setRows(5);
        jScrollPane1.setViewportView(taProfile);

        jProfilePics.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jProfilePics.setPreferredSize(new java.awt.Dimension(240, 240));

        javax.swing.GroupLayout jProfilePicsLayout = new javax.swing.GroupLayout(jProfilePics);
        jProfilePics.setLayout(jProfilePicsLayout);
        jProfilePicsLayout.setHorizontalGroup(
            jProfilePicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jProfilePicsLayout.setVerticalGroup(
            jProfilePicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        jTabMedia.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        PhotoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "POTO" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(PhotoList);

        jTabMedia.addTab("Photo", jScrollPane2);

        VideoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "PIDEO" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(VideoList);

        jTabMedia.addTab("Video", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProfilePics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jProfilePics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabMedia.getAccessibleContext().setAccessibleName("Media");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> PhotoList;
    private javax.swing.JList<String> VideoList;
    private javax.swing.JPanel jProfilePics;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabMedia;
    private javax.swing.JTextArea taProfile;
    // End of variables declaration//GEN-END:variables
}
